### ISSUE TITLE
Show error message if mod has invalid Info.json structure

### ISSUE THREAD

**Issue by Sirgilly** [revblaze/BaldursModManager#25]
This all seemed to be working great but after 8 mods it no longer lets me add new mods. I select them in finder but nothing pops up. I didn't change any settings so not sure why this would be the case. Any ideas?

**Comment by Sirgilly** [comment]
tried deleting a mod and adding another, turns out adding any mods has been disabled

**Comment by revblaze** [comment]
Hey @Sirgilly, thank you for bringing this to my attention! Just checking in – did you manage to resolve this fully, as per the [Nexus post](https://www.nexusmods.com/baldursgate3/mods/5848?tab=posts)? 

It seems like the issue has something to do with a mod author not properly implementing the `Info.json` file. Is there any chance you could send me the mod in question? 

I can maybe look into adding some additional error handling in a future update. For example, if a user attempts to add a mod with a JSON file with an invalid structure; instead of simply rejecting the mod outright, I could prompt the user to manually enter the details themselves (or, at the very least, provide more insight as to why the mod is being rejected to begin with).

**Comment by Sirgilly** [comment]
Yes, thank you. It was not your fault at all. A great tool. A useful
addition might be a little message to say it’s an invalid json file rather
than nothing happening but other than that I was able to fix the json
myself.

**Comment by revblaze** [comment]
I'm on the case! Thank you again for reporting this @Sirgilly.

**Comment by bpengu1n** [comment]
Would be really cool to bypass info.json altogether and read the .pak files directly, as they contain the metadata needed (BG3 MM on Windows uses LSLib to read them, they're a proprietary archive format, that contain metadata XML files with the other mod data -- https://github.com/Norbyte/lslib/blob/master/LSLib/LS/PackageFormat.cs)

**Comment by jav-12** [comment]
Great job. Unfortunately I have some mods that does not have the json file in place and mod does not install. any way to bypass this validation?

**Comment by buzsh** [comment]
@bpengu1n Thanks for sharing! I didn't even know the .NET SDK was available for Mac. I'll look into making a CLI package that I could implement into BaldursModManager when I get a minute.

If this is something that could work, I could refactor the program to manage independent PAK files instead of having to map each PAK file to their JSON counterpart using a local database.

**Comment by buzsh** [comment]
Feel free to open a new issue with the request for XML extraction of PAK files!

I'm closing this specific issue now since the latest version fulfills the issue requirement and notifies the user of missing or incompatible JSON types:

<img width="985" alt="Screenshot 2024-05-27 at 3 22 42 PM" src="https://github.com/revblaze/BaldursModManager/assets/158503966/e3ea4532-a461-4486-832e-40d23d553156">
<img width="985" alt="Screenshot 2024-05-27 at 3 23 59 PM" src="https://github.com/revblaze/BaldursModManager/assets/158503966/b3d86098-4c8a-4801-9a63-48426c96c0cf">
